var myString;
var myNum;
var myBool;
var myVar;
var strArr;
var numArr;
var strNumTupple;
var myVoid = null;
myString = 'hello from ts i love u';
myNum = 2;
myBool = false;
myVar = true;
strArr = ['hello', 'world'];
numArr = [1, 2, 3];
strNumTupple = ['hi', 1];
console.log(myString, myNum, myBool, strArr, numArr, strNumTupple, myVoid);
